import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  numeric,
  pgTable,
  smallint,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { fk, timestamps } from './_shared';
import { donationMethod, donationStatus, localeCode } from './enums';
import { mediaAssets } from './media';
import { profiles } from './profiles';
import { projects } from './projects';

/**
 * Donations — by bank transfer, iBuraq or a card payment page, all to the
 * organisation's own accounts at Bank of Palestine.
 *
 * The site never takes money itself and never sees a card number. What it
 * holds is (1) the account details donors transfer to, edited in the admin
 * and never written in code, and (2) the notices donors send afterwards —
 * "I transferred 100 USD on this date, reference X" — which staff match
 * against the bank statement and confirm or reject.
 *
 * The currencies are the four Bank of Palestine keeps accounts in
 * (`DONATION_CURRENCIES` in `lib/donations/options.ts`; the CHECKs below
 * repeat them for the database).
 */

/**
 * The page's settings. One row, `id = 1`, like `organization_settings`.
 *
 * Kept apart from `organization_settings` because writing it is a different
 * permission: an account number on this page decides where a donor's money
 * goes, so only an admin may change it — the database says so too.
 */
export const donationSettings = pgTable(
  'donation_settings',
  {
    id: smallint().primaryKey().default(1),
    /** Off: the donate page explains how to reach the organisation instead. */
    isEnabled: boolean().notNull().default(false),

    introAr: text(),
    introEn: text(),

    /** iBuraq (the Palestine Monetary Authority's instant-payment system). */
    iburaqAlias: text(),
    iburaqQrMediaId: uuid(),

    /** The bank's hosted card-payment page, once a merchant agreement exists. */
    cardPaymentUrl: text(),

    /** Shown after a notice is sent and in the donor's email. */
    thankYouAr: text(),
    thankYouEn: text(),

    /** Who hears about a new notice, beyond MAIL_TO_GENERAL. */
    notifyEmails: text().array().notNull().default(sql`'{}'::text[]`),

    ...timestamps(),
    updatedBy: uuid(),
  },
  (t) => [
    fk('donation_settings_iburaq_qr_media_id_fkey', t.iburaqQrMediaId, mediaAssets.id, 'set null'),
    fk('donation_settings_updated_by_fkey', t.updatedBy, profiles.id, 'set null'),
    check('donation_settings_singleton', sql`${t.id} = 1`),
    check(
      'donation_settings_card_url_https',
      sql`${t.cardPaymentUrl} is null or ${t.cardPaymentUrl} ~ '^https://'`,
    ),
  ],
);

export type DonationSettings = typeof donationSettings.$inferSelect;

/**
 * One bank account, in one currency.
 *
 * Bank of Palestine opens a sub-account per currency under one account number,
 * each with its own IBAN, so a row is a currency rather than an account.
 */
export const donationAccounts = pgTable(
  'donation_accounts',
  {
    id: uuid().primaryKey().defaultRandom(),
    currency: text().notNull(),
    bankNameAr: text().notNull(),
    bankNameEn: text(),
    branchAr: text(),
    branchEn: text(),
    beneficiaryAr: text().notNull(),
    beneficiaryEn: text(),
    accountNumber: text().notNull(),
    iban: text().notNull(),
    swift: text(),
    sortOrder: integer().notNull().default(0),
    isActive: boolean().notNull().default(true),
    ...timestamps(),
    createdBy: uuid(),
    updatedBy: uuid(),
  },
  (t) => [
    fk('donation_accounts_created_by_fkey', t.createdBy, profiles.id, 'set null'),
    fk('donation_accounts_updated_by_fkey', t.updatedBy, profiles.id, 'set null'),
    check('donation_accounts_currency', sql`${t.currency} in ('ILS', 'USD', 'EUR', 'JOD')`),
    /** A Palestinian IBAN: PS, two check digits, four letters, 21 characters. */
    check('donation_accounts_iban_shape', sql`${t.iban} ~ '^PS[0-9]{2}[A-Z]{4}[0-9A-Z]{21}$'`),
    check(
      'donation_accounts_swift_shape',
      sql`${t.swift} is null or ${t.swift} ~ '^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$'`,
    ),
    index('donation_accounts_order_idx').on(t.sortOrder),
  ],
);

export type DonationAccount = typeof donationAccounts.$inferSelect;

/**
 * A donor's notice that they sent money, and what staff found.
 *
 * Kept for good — no `purge_after`. These are financial records, and the
 * charitable-associations law requires the books of donations to be kept with
 * their supporting documents.
 */
export const donations = pgTable(
  'donations',
  {
    id: uuid().primaryKey().defaultRandom(),
    /** `PCS-DON-XXXXXXXX`, generated by a trigger. */
    reference: text().notNull().unique('donations_reference_key'),
    locale: localeCode().notNull().default('ar'),
    status: donationStatus().notNull().default('pending'),

    method: donationMethod().notNull(),
    /** `numeric(12,2)`, read as a string so no amount is rounded. */
    amount: numeric({ precision: 12, scale: 2 }).notNull(),
    currency: text().notNull(),
    accountId: uuid(),
    transferredOn: date(),
    /** The bank's transaction reference, as the donor gives it. */
    bankReference: text(),
    /** What the gift is for; null means wherever it is needed most. */
    projectId: uuid(),

    donorName: text(),
    donorEmail: text(),
    donorPhone: text(),
    /** Asked not to be named in anything the organisation publishes. */
    isAnonymous: boolean().notNull().default(false),
    wantsReceipt: boolean().notNull().default(false),
    message: text(),
    /** The transfer slip, in the private `applications` bucket. */
    attachmentPath: text(),

    confirmedAmount: numeric({ precision: 12, scale: 2 }),
    receiptNumber: text(),
    reviewedBy: uuid(),
    reviewedAt: timestamp({ withTimezone: true }),
    internalNote: text(),

    ipHash: text(),
    userAgent: text(),
    ...timestamps(),
  },
  (t) => [
    fk('donations_account_id_fkey', t.accountId, donationAccounts.id, 'set null'),
    fk('donations_project_id_fkey', t.projectId, projects.id, 'set null'),
    fk('donations_reviewed_by_fkey', t.reviewedBy, profiles.id, 'set null'),
    check('donations_currency', sql`${t.currency} in ('ILS', 'USD', 'EUR', 'JOD')`),
    check('donations_amount_positive', sql`${t.amount} > 0`),
    check(
      'donations_reviewed_shape',
      sql`${t.status} = 'pending' or (${t.reviewedAt} is not null and ${t.reviewedBy} is not null)`,
    ),
    check(
      'donations_confirmed_shape',
      sql`${t.status} <> 'confirmed' or ${t.confirmedAmount} is not null`,
    ),
    check(
      'donations_text_lengths',
      sql`coalesce(char_length(${t.donorName}), 0) <= 120
        and coalesce(char_length(${t.donorEmail}), 0) <= 320
        and coalesce(char_length(${t.donorPhone}), 0) <= 40
        and coalesce(char_length(${t.bankReference}), 0) <= 100
        and coalesce(char_length(${t.message}), 0) <= 1000`,
    ),
    index('donations_status_idx').on(t.status, t.createdAt.desc()),
    index('donations_project_idx').on(t.projectId),
  ],
);

export type Donation = typeof donations.$inferSelect;
