import { sql } from 'drizzle-orm';
import {
  boolean,
  customType,
  date,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { localeCode, submissionState, submissionType } from './enums';
import { profiles } from './profiles';

/**
 * `bytea` ⇄ `Buffer`. Drizzle has no built-in bytea column.
 *
 * `fromDriver` is not decoration: postgres-js hands back a `Buffer` while
 * PGlite hands back a bare `Uint8Array`. Both satisfy `node:crypto`, so the
 * difference survives every decrypt — but `Uint8Array.prototype.toString`
 * ignores its argument and returns comma-separated byte values, so
 * `blob.toString('utf8')` silently produces garbage instead of text. Normalising
 * here means the declared type is true under every driver.
 */
const bytea = customType<{ data: Buffer; driverData: Uint8Array }>({
  dataType: () => 'bytea',
  fromDriver: (value) => Buffer.from(value),
  toDriver: (value) => value,
});

/**
 * Every public form lands here — six types, one table.
 *
 * Two privacy properties are structural rather than procedural:
 *
 * - `ipHash` and `userAgent` are nullable, and the submission service writes
 *   `null` to both whenever `isSensitive` is true. No caller can opt out,
 *   because no caller supplies them (DNH-8).
 * - `payload` is nullable and `payloadEncrypted` exists beside it. A sensitive
 *   submission stores ciphertext only; the plaintext column stays `null`, so a
 *   database dump of a complaint reveals nothing without the key named by
 *   `payloadKeyId`.
 *
 * `purgeAfter` is set at insert from the retention table in the service, so
 * retention cannot be forgotten at write time and does not depend on a later
 * migration to backfill.
 */
export const formSubmissions = pgTable(
  'form_submissions',
  {
    id: uuid().primaryKey().defaultRandom(),
    /** `PCS-XXXXXX`, generated by a trigger when not supplied. */
    reference: text().notNull().unique(),
    type: submissionType().notNull(),
    isSensitive: boolean().notNull().default(false),
    locale: localeCode().notNull().default('ar'),

    /** Plaintext body. Null for sensitive submissions. */
    payload: jsonb().$type<Record<string, unknown>>(),
    /** AES-256-GCM ciphertext. Null for ordinary submissions. */
    payloadEncrypted: bytea(),
    /** Which key encrypted `payloadEncrypted`, so keys can be rotated. */
    payloadKeyId: text(),

    /** Object path in the private `applications` bucket. */
    attachmentPath: text(),

    state: submissionState().notNull().default('new'),
    handledBy: uuid().references(() => profiles.id, { onDelete: 'set null' }),
    handledAt: timestamp({ withTimezone: true }),
    internalNote: text(),

    /** `sha256(ip + IP_HASH_SALT)`. Never a raw address. Null when sensitive. */
    ipHash: text(),
    /** Null when sensitive. */
    userAgent: text(),

    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    purgeAfter: date().notNull(),
  },
  (t) => [
    index('submissions_type_idx').on(t.type, t.createdAt.desc()),
    index('submissions_state_idx').on(t.state).where(sql`${t.state} = 'new'`),
    index('submissions_purge_idx').on(t.purgeAfter),
    index('submissions_sensitive_idx').on(t.isSensitive, t.createdAt.desc()),
  ],
);

export type FormSubmission = typeof formSubmissions.$inferSelect;
export type NewFormSubmission = typeof formSubmissions.$inferInsert;
