-- Removes `public.generate_submission_reference()`.
--
-- Hand-written, like 0006, 0007 and 0009. The file name is kept from the first
-- draft, which only pinned the function's search_path; it had not been applied
-- anywhere when it was rewritten.
--
-- The function exists on the live database only. No code, trigger or column
-- default calls it (`pg_depend` shows no dependents) — `form_submissions.
-- reference` is written by `app.submit_form()`. But it sits in `public` with
-- EXECUTE granted to PUBLIC, so PostgREST exposes it to anyone as
-- `/rest/v1/rpc/generate_submission_reference`, and Supabase's advisor flags
-- its mutable search_path. Pinning the path fixed the second and left the
-- first; a function nothing uses is removed, not hardened.
--
-- `IF EXISTS`, because a database built from `drizzle/` alone (PGlite, a fresh
-- environment) never had it.
DROP FUNCTION IF EXISTS public.generate_submission_reference();
